name: Dependabot
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot Action Secret 
        run: echo -n "${{secrets.TEST}}" | od -A n -t x1
      - name: Dependabot Secret
        run: echo -n "${{secrets.DB}}" | od -A n -t x1
      - name: Dependabot Env Secret
        run: echo -n "${{secrets.ENV}}" | od -A n -t x1
